name: "Update composer-unused.phar"
on:
  repository_dispatch:
    types: [update-plugin]
jobs:
  myEvent:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Download latest phar"
        run: "curl -OL https://github.com/composer-unused/composer-unused/releases/download/${{ github.event.client_payload.tag }}/composer-unused.phar"

      - name: "Commit new phar"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit-message: "Update .phar to version ${{ github.event.client_payload.tag }}"
          file_pattern: "*.phar"
          
      - name: "Determine release body"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const repository = context.repo
            const response = await github.rest.repos.generateReleaseNotes({
              owner: repository.owner,
              repo: repository.repo,
              tag_name: "${{ github.event.client_payload.tag }}",
            });
            core.exportVariable("RELEASE_BODY", response.data.body);

      - name: "Create release"
        uses: "actions/create-release@v1.1.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          body: "${{ env.RELEASE_BODY }}"
          draft: false
          prerelease: false
          release_name: "${{ github.event.client_payload.tag }}"
          tag_name: ${{ github.event.client_payload.tag }}"

      
